services:
    caddy:
        container_name: caddy
        restart: always
        image: caddy:2.3.0
        volumes:
            - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
            - /var/opt/Loggernet/data:/var/opt/Loggernet/data
        ports:
            - 80:80

    loggernet:
        container_name: loggernet
        restart: always
        build: ./loggernet
        ports:
            - 6789:6789
        secrets:
            - SSH_KEY
        volumes:
            - /var/opt/Loggernet/data:/var/opt/CampbellSci/LoggerNet/data
    
    config:
        container_name: config
        restart: always
        build: ./config
        secrets:
            - source: SSH_KEY
              target: /home/wine/.ssh/id_rsa
              uid: '1000'  # wine user's UID
              gid: '1000'  # wine user's GID
              mode: 0600   # read/write for owner only

secrets:
    SSH_KEY:
        file: /git/.ssh/id_ed25519
